# Generated by Django 2.0.3 on 2018-03-16 10:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data sprzedaży')),
            ],
        ),
        migrations.CreateModel(
            name='Product_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='no_name', max_length=200, verbose_name='nazwa')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='cena')),
                ('quantity', models.IntegerField(default=0, verbose_name='Ilość')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_in_moment', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='cena w momencie sprzedaży')),
                ('quantity', models.IntegerField(default=1, verbose_name='Ilość sprzedanych')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Order_base')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Product_base')),
            ],
        ),
    ]
