# Generated by Django 2.0.3 on 2018-04-13 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='no_name', max_length=200, verbose_name='Imię')),
                ('surname', models.CharField(default='no_name', max_length=200, verbose_name='Nazwisko')),
                ('email', models.EmailField(default='', max_length=200, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'klient',
                'verbose_name_plural': 'Klienci',
            },
        ),
        migrations.CreateModel(
            name='Debtor_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_settle', models.BooleanField(default=False, verbose_name='Czy uregulowane')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Client_base')),
            ],
            options={
                'verbose_name': 'dłużnik',
                'verbose_name_plural': 'Dłużnicy',
            },
        ),
        migrations.CreateModel(
            name='On_Shelf_Position_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=50, verbose_name='tag')),
            ],
            options={
                'verbose_name': 'pozycja na półce',
                'verbose_name_plural': 'Dostępne pozycje produktów na półce',
            },
        ),
        migrations.CreateModel(
            name='Order_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data sprzedaży')),
            ],
            options={
                'verbose_name': 'zamówienie',
                'verbose_name_plural': 'Zamówienia',
            },
        ),
        migrations.CreateModel(
            name='Order_extern_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_of_payment', models.CharField(choices=[('G', 'gotówką'), ('P', 'przelew(niezrealizowany)'), ('R', 'przelew(zrealizowany)')], default='G', max_length=1, verbose_name='forma płatności')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extern_order', to='main_app.Client_base')),
            ],
            options={
                'verbose_name': 'zamówienie zewnętrzne',
                'verbose_name_plural': 'Zamówienia zewnętrzne',
            },
        ),
        migrations.CreateModel(
            name='Order_extern_realisation_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='main_app.Order_extern_base')),
            ],
            options={
                'verbose_name': 'zamówienie zewnętrzne - realizacja',
                'verbose_name_plural': 'Zamówienia zewnętrzne - realizacja',
            },
        ),
        migrations.CreateModel(
            name='Product_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='no_name', max_length=200, verbose_name='nazwa')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='cena')),
                ('quantity', models.IntegerField(default=0, verbose_name='Ilość')),
                ('position', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main_app.On_Shelf_Position_base')),
            ],
            options={
                'verbose_name': 'produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='Product_order_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_in_moment', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='cena w momencie sprzedaży')),
                ('quantity', models.IntegerField(default=1, verbose_name='Ilość sprzedanych')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Order_base')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Product_base')),
            ],
            options={
                'verbose_name': 'zamówienie produktu',
                'verbose_name_plural': 'Zamówienie produktów',
            },
        ),
        migrations.CreateModel(
            name='Product_order_extern_realisation_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_in_moment', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='cena w momencie sprzedaży')),
                ('quantity', models.IntegerField(default=1, verbose_name='ilość zamówionych')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Order_extern_realisation_base')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Product_base')),
            ],
            options={
                'verbose_name': 'zamówienie produktu zewnętrzne - realizacja',
                'verbose_name_plural': 'Zamówienia produktów zewnętrzne - realiacja',
            },
        ),
        migrations.CreateModel(
            name='Realisation_tag_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=50, verbose_name='tag')),
            ],
            options={
                'verbose_name': 'status realizacji',
                'verbose_name_plural': 'Tagi statusów realiacji',
            },
        ),
        migrations.CreateModel(
            name='Tag_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=50, verbose_name='tag')),
            ],
            options={
                'verbose_name': 'tag produktu',
                'verbose_name_plural': 'Tagi produktów',
            },
        ),
        migrations.CreateModel(
            name='Tech_tag_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=50, verbose_name='tag')),
            ],
            options={
                'verbose_name': 'tag techniczny produktu',
                'verbose_name_plural': 'Tagi techniczne produktów',
            },
        ),
        migrations.AddField(
            model_name='product_base',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='product', to='main_app.Tag_base'),
        ),
        migrations.AddField(
            model_name='product_base',
            name='tech_tag',
            field=models.ManyToManyField(blank=True, related_name='product', to='main_app.Tech_tag_base'),
        ),
        migrations.AddField(
            model_name='order_extern_realisation_base',
            name='realisation_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_realisation', to='main_app.Realisation_tag_base'),
        ),
        migrations.AddField(
            model_name='debtor_base',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debtor', to='main_app.Order_base'),
        ),
    ]
