# Generated by Django 2.0.4 on 2018-04-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech_tag_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=50, verbose_name='tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product_order_extern_realisation_base',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='ilość zamówionych'),
        ),
        migrations.AlterField(
            model_name='product_base',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='product', to='main_app.Tag_base'),
        ),
        migrations.AlterField(
            model_name='product_base',
            name='tech_tag',
            field=models.ManyToManyField(blank=True, related_name='product', to='main_app.Tech_tag_base'),
        ),
        migrations.AlterField(
            model_name='realisation_tag_base',
            name='tag',
            field=models.CharField(default='', max_length=50, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='tag_base',
            name='tag',
            field=models.CharField(default='', max_length=50, verbose_name='tag'),
        ),
    ]
