# Generated by Django 2.0.3 on 2018-03-16 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='no_name', max_length=200, verbose_name='nazwa')),
                ('surname', models.CharField(default='no_name', max_length=200, verbose_name='nazwa')),
                ('if_settle', models.BooleanField(default=False, verbose_name='Czy uregulowane')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Debtor', to='main_app.Order_base')),
            ],
        ),
    ]
