# Generated by Django 2.0.3 on 2018-04-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180408_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation_tag_base',
            name='tag',
            field=models.CharField(default='', max_length=50, verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='tag_base',
            name='tag',
            field=models.CharField(default='', max_length=50, verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='tech_tag_base',
            name='tag',
            field=models.CharField(default='', max_length=50, verbose_name='tag'),
        ),
    ]
