# Generated by Django 2.0.3 on 2018-04-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180408_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_base',
            name='tech_tag',
            field=models.ManyToManyField(blank=True, related_name='product', to='main_app.Tech_tag_base'),
        ),
    ]
